# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slash_command', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serializedBoard', models.TextField()),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Won or Lost by someone'), ('D', 'Draw'), ('C', 'Abandoned/Cancelled'), ('A', 'Active')], db_index=True, default='A', max_length=1)),
                ('player1Char', models.CharField(default='X', max_length=1)),
                ('player2Char', models.CharField(default='0', max_length=1)),
                ('nullChar', models.CharField(default=' ', max_length=1)),
                ('nRows', models.IntegerField()),
                ('nCols', models.IntegerField()),
                ('numConsecutiveCoinsToWin', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='GameChannels',
            new_name='GameChannel',
        ),
        migrations.RenameModel(
            old_name='GameUsers',
            new_name='GameUser',
        ),
        migrations.AddField(
            model_name='game',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='slash_command.GameChannel'),
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='slash_command.GameUser'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='slash_command.GameUser'),
        ),
        migrations.AddField(
            model_name='board',
            name='currentTurn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='slash_command.GameUser'),
        ),
        migrations.AddField(
            model_name='board',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='slash_command.Game'),
        ),
    ]
